# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Parslee.Car
PackageVersion: 0.24.0
InstallerType: zip
NestedInstallerType: portable
Commands:
  - car
  - car-server
  - car-memgine-eval
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Parslee-ai/car-releases/releases/download/v0.24.0/car-win32-x64-msvc.zip
    InstallerSha256: 5F60646DF17C4C0ADA142EBE56D8D88C9FF572483390EABBACB8D69259F75243
    NestedInstallerFiles:
      - RelativeFilePath: car.exe
        PortableCommandAlias: car
      - RelativeFilePath: car-server.exe
        PortableCommandAlias: car-server
      - RelativeFilePath: car-memgine-eval.exe
        PortableCommandAlias: car-memgine-eval
ReleaseDate: 2026-06-14
ManifestType: installer
ManifestVersion: 1.6.0
