# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Parslee.Car
PackageVersion: 0.46.1
InstallerType: zip
NestedInstallerType: portable
Commands:
  - car
  - car-server
  - car-memgine-eval
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Parslee-ai/car-releases/releases/download/v0.46.1/car-win32-x64-msvc.zip
    InstallerSha256: B18F86F195F59804D26932E58B1721F04087ED94367A4CFABA1A7C4CC4950B95
    NestedInstallerFiles:
      - RelativeFilePath: car.exe
        PortableCommandAlias: car
      - RelativeFilePath: car-server.exe
        PortableCommandAlias: car-server
      - RelativeFilePath: car-memgine-eval.exe
        PortableCommandAlias: car-memgine-eval
ReleaseDate: 2026-08-06
ManifestType: installer
ManifestVersion: 1.6.0
