# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Parslee.Car
PackageVersion: 0.22.0
InstallerType: zip
NestedInstallerType: portable
Commands:
  - car
  - car-server
  - car-memgine-eval
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Parslee-ai/car-releases/releases/download/v0.22.0/car-win32-x64-msvc.zip
    InstallerSha256: 1D4D172D9445B11F2687BB8DE33464CEA637C6A2C0C741E5BCC0D536C921E7C1
    NestedInstallerFiles:
      - RelativeFilePath: car.exe
        PortableCommandAlias: car
      - RelativeFilePath: car-server.exe
        PortableCommandAlias: car-server
      - RelativeFilePath: car-memgine-eval.exe
        PortableCommandAlias: car-memgine-eval
ReleaseDate: 2026-06-05
ManifestType: installer
ManifestVersion: 1.6.0
