# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Parslee.Car
PackageVersion: 0.26.0
InstallerType: zip
NestedInstallerType: portable
Commands:
  - car
  - car-server
  - car-memgine-eval
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Parslee-ai/car-releases/releases/download/v0.26.0/car-win32-x64-msvc.zip
    InstallerSha256: A6A0760C90880C9F8C65AEADC54BDC3D75CDED1789FF7863696A7F0B33910B87
    NestedInstallerFiles:
      - RelativeFilePath: car.exe
        PortableCommandAlias: car
      - RelativeFilePath: car-server.exe
        PortableCommandAlias: car-server
      - RelativeFilePath: car-memgine-eval.exe
        PortableCommandAlias: car-memgine-eval
ReleaseDate: 2026-06-17
ManifestType: installer
ManifestVersion: 1.6.0
